# Generated by Django 4.2.3 on 2023-07-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='passwords',
            new_name='color',
        ),
    ]
