# Generated by Django 4.2.3 on 2023-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0002_rename_passwords_passwords_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
