# Generated by Django 4.2.3 on 2023-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0003_alter_passwords_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=200)),
            ],
        ),
    ]
