# Generated by Django 4.2.1 on 2023-07-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0005_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answers',
        ),
    ]
