# Generated by Django 4.2.1 on 2023-07-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0007_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gas_app.chats'),
        ),
    ]
