# Generated by Django 4.2.1 on 2023-07-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0010_alter_answers_answer_alter_answers_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question',
            new_name='questions',
        ),
    ]
